{pkgs, ...}:
{
    nixpkgs.config.allowUnfree = true;
    environment.systemPackages = with pkgs; [
            ansible
            aria2
            atuin
            bat
            btop
            bun
            chromium
            cmake
            curl
            eza
            fastfetch
            fd
            feh
            fzf
            git
            go
            htop
            imagemagick
            jq
            just
            lazydocker
            lazygit
            libnotify
            lua51Packages.luarocks
            #lutris
            meson
            mpdris2
            mpv
            gnumake
            ncdu
            netcat
            ninja
            nmap
            nwg-look
            obs-studio
            obsidian
            pavucontrol
            postgresql
            pywal16
            qbittorrent
            ranger
            rclone
            ripgrep
            rofi
            #rustdesk
            rustup
            tailscale
            #terraform
            terminus_font
            thunar
            thunar-volman
            tumbler
            tmux
            virt-top
            virt-viewer
            virt-manager
            vim 
            vlc
            wget
            wireshark
            wl-clipboard
            wl-mirror
            xwayland-satellite
            yt-dlp
            zathura
            zathuraPkgs.zathura_pdf_poppler
            zoxide
    ];
}
